### ISSUE TITLE
[FR] GadgetBridge data fetching

### ISSUE THREAD

**Issue by ildar** [dennisguse/OpenTracks#40]
As the app supports heart rate then it's easier getting it from a fitness tracker. And subj is one open platform which can provide this info from a number of fitness trackers. Gpx available from some trackers too.

**Comment by dennisguse** [comment]
Any suggestions on how to implement this?

**Comment by dennisguse** [comment]
I just thought about this: OpenTracks stores the data for each captures GPS position (i.e., one heart rate entry per position). So importing heart rate alone is technically not an option. In addition, the connection to the heart rate sensor (Bluetooth LE) only can read the actual heart rate and no historic data from the device.

The easiest way to import data would be to provide them as GPX/KML (and include the heart rate as additional data).
If you think this might be worth the effort please open a new issue.
