### ISSUE TITLE
Description: add spanish translation

### ISSUE THREAD

**Issue by dennisguse** [dennisguse/OpenTracks#43]
Will be shown in Fdroid.

**Comment by xmi** [comment]
Hi! What exactly is to be translated?

**Comment by dennisguse** [comment]
The descriptions files:
* full_description.txt
* short_description. txt

It is the description used for the Fdroid store.

El October 19, 2019 8:45:13 PM UTC, xmi <notifications@github.com> escribió:
>Hi! What exactly is to be translated?

-- 
Dennis Guse

**Comment by dennisguse** [comment]
Here is a draft: https://github.com/dennisguse/OpenTracks/tree/translationSpanish

**Comment by dennisguse** [comment]
Thanks to @i82orbom!
