### ISSUE TITLE
 No GPS data 

### ISSUE THREAD

**Issue by r4taw2mg** [dennisguse/OpenTracks#56]
Hi,

The installation on my Sony Z3 does not work. The app is not getting any gps data. GPS is turned on, location permission has been granted. Other apps (e.g. osmAnd) do work. Rooted D6603 running Android 6.0.1.

**Comment by dennisguse** [comment]
Thanks for the report.
Just a quick guess: Did you change the _GPS accuracy_ setting?
And if not could you set it to a larger value?
I just realized -really 20min ago- that this setting might be misleading; basically all GPS coordinates are filtered before actually being processed if their accuracy is larger than the threshold.

If this does not solve the issue:
Could you provide some more information:
* which version of OpenTracks do you use (can be found in the Settings)?
* what OS do you run (e.g., Sony original or LineageOS)?

And would be possible to get a logcat output (when starting a recording)?

**Comment by r4taw2mg** [comment]
Hi, 

thanks for your assistance. I didn't change any of the GPS settings and it was Sony firmware. But I made an update and it worked with the new version. (I was one release behind).

I am closing the ticket.

Cheers
Frank

**Comment by dennisguse** [comment]
Interesting that the bug fixed itself as the new version 3.2.3 as well as 3.2.4 did not contain any changes that are related to the GPS.
So, if you encounter the issue again - please reopen this issue.

If you have any other feedback and see room for improvement - let me know.

**Comment by r4taw2mg** [comment]
I understand. Nonetheless that was my experience.

I don't get any notification on my lock screen. Some permissions missing?
