### ISSUE TITLE
Please re-add support for ANT+ and Classic Bluetooth,

### ISSUE THREAD

**Issue by pes4murai** [dennisguse/OpenTracks#73]
I have a KALENJI DUAL ANT+ / BLUETOOTH SMART RUNNER'S HEART RATE MONITOR BELT (https://www.decathlon.co.uk/ant-bluetooth-smart-hrm-id_8334795.html).
It uses Bluetooth Smart (4.0) et ANT+ communication technology and I cannot pair with the app.

Please could you re-add the support for ANT+ and Classic Bluetooth?

Thank you for your amazing work, your app is great.

Regards,

**Comment by dennisguse** [comment]
This tracker should actually work as it supports Bluetooth low energy (BLE) aka Bluetooth Smart.
I have the feeling that BLE is supported almost always if ANT+ is supported (my Polar OH1 has also dual support).
In the upcoming release v3.2.6, a proper Bluetooth scan is implemented.
For the time being, can you check with an app like BLExplorer (https://f-droid.org/en/packages/org.ligi.blexplorer/) if your heart rate monitor supports BLE?


Anyhow, readding ANT+ is (at the moment) not an option as it requires introducing an additional library (got also requested in #63).
From my perspective making OpenTracks maintainable is more important than adding ANT+.
If someone wants to take the effort (incl. maintenance), please do.
