### ISSUE TITLE
Disable screen from turning off while tracking

### ISSUE THREAD

**Issue by edern-appere** [dennisguse/OpenTracks#80]
In the settings there is an option to display the app on the lock screen. It would be great if there was an option in OpenTracks settings to disable the screen from turning off (like any GPS navigation app does) while the app is running.

This would allow using OpenTracks as a replacement for a bike computer for example since it displays in real time the data. Of course it would use a little bit of juice from the battery.

A special screen setup for bike to ease the reading of information while riding would even be more awesome. For example having speed displayed in big and bold while other information in regular font.

**Comment by dennisguse** [comment]
@edern-appere I just implemented this functionality.
You now can select this option in the settings (similar to the lockscreen option).
In addition, there was a bug in lockscreen option (even when not recording it was shown without unlocking the device).
The feature will be released in v3.2.9 - should be on Fdroid before the weekend.

Thanks for the idea!
