### ISSUE TITLE
GPS Fix alert

### ISSUE THREAD

**Issue by pes4murai** [dennisguse/OpenTracks#81]
Is it possible to add a sign (or colored button) near the GPS switch that advise when the GPS is fixed?

**Comment by dennisguse** [comment]
Yes, it is on the roadmap although with low priority (see #37).
For the moment, v3.2.7 will use a notification (that was already present) showing feedback about the GPS accuracy.
Also, the notification will pop up (and notify the user) if the accuracy goes beyond the the user-defined threshold.
