### ISSUE TITLE
Heart Rate recorded but not shown 

### ISSUE THREAD

**Issue by serpico** [dennisguse/OpenTracks#82]
**Describe the bug**
Description looks similar to #50 
While recording the heart rate is not shown on the Statistic tab see :
![Screenshot_2019-11-22-15-36-57](https://user-images.githubusercontent.com/1227077/69792915-c89b3380-11c7-11ea-843e-ec08fd90bd12.png)

Although when displaying the graphical tab it seems to be recorded :+1: 
![Screenshot_2019-11-22-16-46-28](https://user-images.githubusercontent.com/1227077/69793048-06985780-11c8-11ea-85c4-aba2fb8cdc59.png)

**Technical information**
 - Device: Samsung SM-G361F
 - OS: Android 5.1.1
 - Version v3.2.6

**Comment by dennisguse** [comment]
Thanks for the report.
It would be very helpful, if you could figure out how to reproduce this problem.
For example, did you put OpenTracks in the background (in between using another app) or did navigate within OpenTracks?

**Comment by pes4murai** [comment]
![Screenshot_2019-11-30-09-18-11-357_de dennisguse opentracks](https://user-images.githubusercontent.com/43846940/69977571-56aa4d80-152b-11ea-9992-8b5c9dd0e95b.jpg)

Same here, using OpenTracks not in background but leaving the system always on during the run with the app opened

**Comment by dennisguse** [comment]
Is the heart rate not shown at all or does it vanish?

PS: No changes in v3.2.8 that would affect this behavior (should be on Fdroid tomorrow).

**Comment by dennisguse** [comment]
Sometimes coding in the evening is not a good idea.
While cleanup, I removed the code to set the heart rate sensor value to the UI...
Fix will be included in v3.2.9.

**Comment by bschwehn** [comment]
I have the same issue in v4.2.0 / 5119. Heart rate is recorded and shown in the graph, but the heart rate widget in the dashboard/stats view never displays the BPM.

**Comment by dennisguse** [comment]
@bschwehn actually no; see #1426. 
In V4.2.0, this functionality was removed as some refactoring was required and needs to be reimplemented. 

You could use remain using v4.1.0 for now until this feature is re-added.

**Comment by bschwehn** [comment]
@dennisguse Ah, great! I downgraded to 4.1.1 for now and the heartrate is showing now.

Thanks a lot for all the work you've put into opentracks!
